version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: pet_shop_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pet_shop
      PG_DATA: /var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres-network

  spring_boot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet_shop_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pet_shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring-boot-postgres-network

networks:
  spring-boot-postgres-network:

volumes:
  pg-data:
